### ISSUE TITLE
Half star not working for display

### ISSUE THREAD

**Issue by LevytsRoman** [Extrct/react-native-stars#12]
Hi, just tried using the stars component to display some stars and the half star is working for the selection but not display. Any help, suggestion on whats going on?

```
            <Stars
              value={4.5}
              spacing={0.8}
              half={true}
              count={5}
              starSize={20}
              backingColor="cornsilk"
              halfStar={require('../../assets/icons/star_half.png')}
              fullStar={require('../../assets/icons/star_filled.png')}
              emptyStar={require('../../assets/icons/star_empty.png')}/>
```

**Comment by 4umo** [comment]
Hi Roman,

I've just tested this code and it appears to work on my iPhone - are you
developing on android? What is your expected behavior? Also - you don't
need to include the `half` property in display mode, passing the `value`
property will override and ignore the half star selection behavior.

Best,
Austin

**Comment by LevytsRoman** [comment]
Thanks for the quick response,

I'm currently working in an Android emulator Android 8.1, 
haven't yet tested on an iPhone. (Don't have access to a mac atm, so will test later).

With display mode it rounds down to nearest integer and displays an emptyStar image in place of halfStar. For example if I pass value={3.5} I'll see 3 full stars and 1 empty. Expected to see 3 full stars and 1 half star.

I've got it to work for now by using a selection mode and setting disabled={true} and passing in rating prop.

**Comment by 4umo** [comment]
Ah okay, I'll take a look at the android display mode behavior when I've
got a chance - it'll take some time to get the android testing setup
running again. There may be a breaking change with how android displays
layered image/background image components. Thanks for the heads up on this.

Best,
Austin

**Comment by tamdao** [comment]
Take a look my PR: https://github.com/Extrct/react-native-stars/pull/15

**Comment by 4umo** [comment]
Hi Roman,
So I've just tested on Android and display mode appears to work just fine with values like 3.5 - is this still an issue? Also, is the code you posted the exact code you're using? If not can you reply with the exact properties you're using, thanks.

**Comment by LevytsRoman** [comment]
It is the exact code, but I no longer have access to the project I was working on. 
Thanks for looking into it.

**Comment by 4umo** [comment]
Understood - I'm going to close this issue for now then, thanks for bringing this up!

**Comment by GendelfLugansk** [comment]
Hello. This is still an issue when custom icon components are used
