### ISSUE TITLE
on Android wrong number of starts are displayed

### ISSUE THREAD

**Issue by benonymus** [Extrct/react-native-stars#14]
Hey there,
I calculate the number of starts by adding 2 values and splitting it, and i log the value, it is correct, but when i pass it to the star's value property and display it it shows always 1 more star.
for example (1+5)/2 =3 right but it displays 4 stars
here is my star component:
```
<Stars
      value={props.data.rating}
      half={props.half}
      spacing={8}
      count={5}
      starSize={50}
      backingColor="transparent"
      fullStar={require("./../icons/filled-heart.png")}
      emptyStar={require("./../icons/empty-heart.png")}
      halfStar={require("./../icons/half-heart.png")}
    />
```
also it does the same if i just put in a number for value

**Comment by 4umo** [comment]
Hi benonymus,
I haven't had a chance to look deeply into this issue yet- but I seems as
though there may have been a breaking change for this component in the
android environment. I'll look at refactoring the component in the coming
weeks if possible. Apologies if this delays your development.
Best,
Austin

**Comment by 4umo** [comment]
Hi benonymus, so looking back at this - the issue is that you've got `backingColor="transparent"`- this module requires that you use a non transparent backingColor/backgroundColor when using display mode (passing a `value` property)
