### ISSUE TITLE
默认数量，无法设置？

### ISSUE THREAD

**Issue by chenyinlong** [Extrct/react-native-stars#16]
设置default 和display 时，没有显示相应的星级，并没有报错，请问是什么情况？

**Comment by simsungyong** [comment]
TypeError: Json.stringify cannot serialize cyclic structures error arise in index.js
how can i fix

**Comment by tayguohong** [comment]
> TypeError: Json.stringify cannot serialize cyclic structures error arise in index.js
> how can i fix

I am facing this issue too. Do you have any solutions?

**Comment by 4umo** [comment]
these issues should be resolved in the most recent release (1.2.1). Let me know if these are still occurring afterward and I will open the issue again.
