### ISSUE TITLE
how make star readonly

### ISSUE THREAD

**Issue by sunihegde** [Extrct/react-native-stars#18]

**Comment by 4umo** [comment]
depending on the use case, either
```
<Stars
...
disabled={true}
>
```
or
```
<Stars
...
display={your_fixed_value}
>
```

**Comment by sunihegde** [comment]
readonly={true }
Is not working for me

**Comment by 4umo** [comment]
right, there's no readonly property observed by this component, have you tried `disabled={true}`?
