### ISSUE TITLE
Cannot Set Value for display props

### ISSUE THREAD

**Issue by tayguohong** [Extrct/react-native-stars#20]
I am following the documentation to display partial rating, but display props throw errors when i pass the rating state into it.

The error message is as follows:

Json.stringify cannot serialize cyclic structure.

Any solution to solve this issue?

**Comment by 4umo** [comment]
Will take a look this weekend - thanks for bringing this up!

**Comment by tayguohong** [comment]
> Will take a look this weekend - thanks for bringing this up!

Thank you for writing this library. After i do some inspection in my code. I found out there is no problem when i implement the star rating using local image, but there is issue when i try to use icon component from Ionicon. And one more question, is there anyway to standardise the display of star rating in partial format? Because the display of 0.1 and 0.9 rating are too similar with 0 and 1 rating.

**Comment by 4umo** [comment]
the JSON.stringify issue should be solved as of the most recent release - so I'll be closing this issue.

On a separate note: I've noticed this issue as well - I will add a note in the Roadmap in the README about adding a partial display amounts interpolation feature which would give a more natural look and feel to marginal partial display amounts like .1 and .9
