### ISSUE TITLE
Fix published npm version

### ISSUE THREAD

**Issue by willmcclellan** [Extrct/react-native-stars#27]
The current version of the package npm looks like it has a rogue typescript file included. This causes issues with type checking locally because it's automatically pulled in as a source file. Can this be republished with the `index.ts` file?

![image](https://user-images.githubusercontent.com/875453/93562924-45530480-f9ca-11ea-917f-a7816165fa1e.png)

**Comment by 4umo** [comment]
Hi Will,

Thanks for identifying this, yeah we can definitely clean that up. Thanks!

**Comment by 4umo** [comment]
should be resolved now, let me know if you encounter any additional issue. Thanks man 👍
