### ISSUE TITLE
Support for Expo icons

### ISSUE THREAD

**Issue by arronhunt** [Extrct/react-native-stars#6]
It would be great if this library supported expo vector icons in addition to images.

```jsx
import MaterialIcons from '@expo/vector-icons';

<Stars
   fullStar={<MaterialIcons name='star' />}
/>
```

**Comment by peacechen** [comment]
I've started work on supporting components for the star props.  It's taking longer than expected due to the opaque / bar renderings.  Hopefully will be done within a day or so.

**Comment by peacechen** [comment]
Here's an example using MaterialCommunityIcons along with textShadow styling:
![screen shot 2018-01-18 at 12 04 59 pm](https://user-images.githubusercontent.com/6295083/35113671-e4532a5c-fc47-11e7-992b-515bced482d5.png)

Created PR #7 which adds support for custom components.  Updated Readme as well.

Until the PR is merged, you can try it out from my fork
```
    "react-native-stars": "git+https://github.com/peacechen/react-native-stars.git",
```

**Comment by 4umo** [comment]
Support has been added. Kudos to @peacechen!

**Comment by peacechen** [comment]
Thanks @Extrct for the fast merge and release 👍
