### ISSUE TITLE
How to get event when start value change

### ISSUE THREAD

**Issue by anitalanet** [Extrct/react-native-stars#9]
Hi there

I need to call api when the star value gets changes 

So is there any event method which called when star value gets changes Like onChange  op selectedStar etc

Please let me know

Thanks

**Comment by 4umo** [comment]
Hi Anny,
You should be able to give the `update` prop a function like so update={(val
)=>{this.setState({stars: val})}} where `val` is the new value of the star
component when it changes- in this function you can add an api call as
needed. For example:
(val)=> {
  this.setState({stars : val});
  // additional api call
  this.apiCall(val);
}
I hope this helps.
Best,
Austin
